### PR TITLE
Add a feature generating a patch from directories (#283)

### PR DESCRIPTION
**Pull request by tjmprm77**
Add a feature generating a patch from directories in relation to Issue #283.
- Add a feature generating a patch from directories.
- Remove some processing that abort patch generation when attempting to generate a patch from directories.
- Change to open a file or directory selection dialog when clicking [Browse...] buttons in [Patch Generator] dialog.
- Change the behavior if the input is a binary file as follows:
  - Processing is not aborted but continued.
  - "Cannot create a patch file from binary files." message is shown once only at the first time per patch generation process.
  - Even if "Cannot create a patch file from binary files." message is shown, if patch generation succeed for other regular files, "Patch file successfully written." messages is shown.

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you!

**Comment by jimsmithm3** [comment]
@sdottaka Can you think of a reason when I create the patch file output that the filenames are not showing up?   

I am doing what you showed in #1753 but still don't see the filenames if I do it for a single file or a folder and outputting to a file or the clipboard.

Using 2.16.30.0  

[pat1560.txt](https://github.com/WinMerge/winmerge/files/11492846/pat1560.txt)

Thanks for the great tool.

**Comment by sdottaka** [comment]
@jimsmithm3
If you select something other than Normal in the Style combobox of the Patch Generator dialog, the file name will be output.

image

**Comment by jimsmithm3** [comment]
That indeed was the easy fix and I see them now.  Thanks so much for the quick response.

**Pull request merged**
