### PR TITLE
Update of Lithuanian translation

### PR DESCRIPTION
**Pull request by Tichij**

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you!

**Comment by sdottaka** [comment]
I changed the term "Ignore Substitutions" to "Substitution Filters" and lost some translations. I'm sorry that your translation was lost.

**Comment by Tichij** [comment]
@sdottaka ,
Can you explain the context of newly added lines: "Text only", "Line-by-line position and text", "Word-by-word position and text" or where I can see them in the app so I can understand the context myself.
Thanks.

**Comment by sdottaka** [comment]
These are the values displayed in the Compare/Image category → OCR result combo box in the Options dialog.

image

This value affects the results of the menu item Image-> Compare Extracted Text From Image that you can select when comparing images.

Example:

image

- Text Only

image

- Line-by-line position and text

image

- Word-by-word position and text

image

**Pull request merged**
