### PR TITLE
Update Slovenian.po

### PR DESCRIPTION
**Pull request by JadranR**
Please, update Slovenian.po and allow Me that I can changing this file (and download).
With respect,
Jadran

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Hello,
I tried a little harder and found a way to make the changes.

May I change all strings like this:

#, c-format
msgid ""
"\n"
"New Documents (Ctrl+N)"
msgstr ""
"\n"
"Novi dokumenti (Ctrl+N)"

into:

#, c-format
msgid "\nNew Documents (Ctrl+N)"
msgstr "\nNovi dokumenti (Ctrl+N)"

Thanks for Help
Jadran

**Comment by sdottaka** [comment]
Please make a Pull Request.

**Comment by JadranR** [comment]
Finished :-))
Be healthy !

Jadran

V V tor., 24. nov. 2020 ob 10:53 je oseba Takashi Sawanaka <
notifications@github.com> napisala:

**Comment by JadranR** [comment]
I downloaded the WinMerge-2.16.9-Setup.exe version and checked the
Slovenian user interface after installation. Some interface entries do not
appear correctly (translation is already complete). Please see the attached
screenshots.

Best Regards,
Jadran

V V tor., 24. nov. 2020 ob 12:06 je oseba Jadran Rudec <jrudec@gmail.com>
napisala:

**Comment by sdottaka** [comment]
I couldn't see your attachment on the GitHub web.
However, due to the following changes, there are some texts that need to be retranslated, so please retranslate.

https://github.com/WinMerge/winmerge/commit/3efe74fa162bd07a7460e65fac1c58892455f4c3

**Comment by JadranR** [comment]
About
Edite Menu Item- Go to
Menu Item Close
Menu Item Exit
Print Preview
Unpacker Hint

I have translated some again but 'Exit' and 'Close' are already there, but they appear in English ?

**Comment by sdottaka** [comment]
An issue where some text was not translated has been fixed in commit 003c8593c3a687730b1b3bb7628acf8ade1d28ca.

**Comment by JadranR** [comment]
Updated Slovenian.po on Date 14.02.2021

Best regards,
Jadran
[SLO translation.zip](https://github.com/WinMerge/winmerge/files/5978138/SLO.translation.zip)

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Updated Slovenian.po on Date 02.03.2021

[WinMerge-SLO translation-02.03.2021.zip](https://github.com/WinMerge/winmerge/files/6067167/WinMerge-SLO.translation-02.03.2021.zip)


Best regards,
Jadran

**Pull request merged**
