### PR TITLE
Create Midnight.ini

### PR DESCRIPTION
**Pull request by HaroldPetersInskipp**
Added an additional color scheme that is easy on the eyes.

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you for the PR.

The name "Dark Mode" looks strange compared to the other schema names, so could you please remove the "Mode" and name it something else?

Also, as you can see below, the colors of the folder window and other colors have not changed much from Solarized Dark. Can you make them a little different from Solarized Dark?


image

**Comment by HaroldPetersInskipp** [comment]
I have updated and renamed the color scheme to better differentiate it from Solarized Dark.

**Comment by sdottaka** [comment]
Thank you for updading the file.

The diff items in the folder window are a little hard to see for me, is this OK for you?

image

**Comment by HaroldPetersInskipp** [comment]
I've altered the value of the background for diff items in the folder window to better contrast with the text. I didn't want increase the contrast too high here, as that would defeat the purpose of a dark theme, but I think this is a good compromise between ease of readability and lack of eye strain.

**Comment by sdottaka** [comment]
Thank you!

**Pull request merged**
