### PR TITLE
Add a feature to save/restore compare options to/from a project file. (#489)

### PR DESCRIPTION
**Pull request by tjmprm77**
Add a feature to save/restore compare options to/from a project file requested in issue #489.

In this pull request, I changed the behavior of the "Options..." popup menu in the Select Files or Folders dialog. Is that okay?
The reason for this change is as follows.
"Include Subfolders" and file filters are not saved in the WinMerge option when we have loaded the project or change values on the dialog, but are saved in the WinMerge option when we then click the "Compare" button to start the comparison.
I think it's better that the compare options are also saved in the WinMerge option with the same scheme as those.
So I changed the behavior of the "Options" popup menu as follows:
- Even if the values in the popup menu are changed, it is not saved in the WinMerge option at that time.
- The values in the popup menu are saved in the WinMerge options when the "Compare" button is clicked.

Also, due to this change, the "Include Subfolders" item in the popup menu has exactly the same function as the check box and is no longer needed, so it has been deleted.

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you!

>Is that okay?

LGTM. But, I might change GetOptionsMgr()->SaveOption() in the CMergeApp::LoadAndOpenProjectFile() function to GetOptionsMgr()->Set() later. This is to make the change in settings temporary, similar to the behavior of command line options such as /ignorews and /ignorecase.

**Comment by tjmprm77** [comment]
Thank you for your reply.
I am relieved that there seemed to be no problem.

> But, I might change GetOptionsMgr()->SaveOption() in the CMergeApp::LoadAndOpenProjectFile() function to GetOptionsMgr()->Set() later. This is to make the change in settings temporary, similar to the behavior of command line options such as /ignorews and /ignorecase.

Sure, as you say, I think it might be better to apply the compare options as temporary settings when opening the project file, instead of saving them to the WinMerge options.

BTW, although it may have something to do with the above topic, file filters, plugins and comparison options are now always saved/restored to and from the project file, but I think it's useful if users can choose whether or not to save/restore them. 
If you are in favor of adding this feature, I will implement it and send a PR.

**Comment by sdottaka** [comment]
> If you are in favor of adding this feature, I will implement it and send a PR.
I agree with the implementation of that feature.

**Comment by tjmprm77** [comment]
Thank you.
I will start implementing it.

**Pull request merged**
