### PR TITLE
Update Slovenian.po

### PR DESCRIPTION
**Pull request by JadranR**
Please, send Me link for download last Beta version of WinMerge. I had some issues with gmail and lost your email with the link you sent me.  Thank you !
Jadran

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you!

Please refer to the following URL. 
https://github.com/WinMerge/winmerge/issues/858#issuecomment-996632862

**Comment by JadranR** [comment]
Updated Slovenian translation for Frhed, per Today

With respect
Jadran
[sl.zip](https://github.com/WinMerge/winmerge/files/7998282/sl.zip)

**Comment by sdottaka** [comment]
I looked at the attached files and couldn't find any differences other than the line feed code.
Are you sure you didn't attach another file by mistake? (Current sl.po on GitHub: https://github.com/WinMerge/frhed/blob/github/3way-diff-gplv2/Translations/Frhed/sl.po)

By the way, in the sl.po file on GitHub, double quotation marks were missing, so I fixed them as follows.

https://github.com/WinMerge/frhed/commit/19f4a499672b66787ba55836ba82448e2a3352f5

**Comment by JadranR** [comment]
Hi,

On this link this string isn't translated:
msgid "Hex Dump files(*.txt,*.hex)|*.txt;*.hex|All Files (*.*)|*.*|"
msgstr ""

but....My last Slovenian translation is based on sl.po file for last Frhed
application insideWinMerge on
build\Releases\winmerge-2.16.18-f331028f1-x64-exe.zip
<https://ci.appveyor.com/api/buildjobs/f6xa3ru6n5phmjpx/artifacts/build%2FReleases%2Fwinmerge-2.16.18-f331028f1-x64-exe.zip>
.

NOTE: Pleace, replace my last translation into Frhed folder for
installation WinMerge.

Best Regards,
Jadran

V V pet., 4. feb. 2022 ob 00:08 je oseba Takashi Sawanaka <
***@***.***> napisala:

**Comment by sdottaka** [comment]
The translation of "Hex Dump files (* .txt, * .hex) | * .txt; *. Hex | All Files (*. *) | *. * |" was not included in your attached file.

image

However, this translation was found to have been lost due to a bug in the po file update script, so I restored it with the following commit. 

https://github.com/WinMerge/frhed/commit/f135b56284cf68ec0bc0c6b148cc915eb07f8610

**Pull request merged**
