### PR TITLE
Spanish translation update

### PR DESCRIPTION
**Pull request by mauriciogracia**

### CODE REVIEW

**Comment by mauriciogracia** [comment]
@sdottaka this is work in progress for the Spanish (Latin American) version, I would say 75% of the messages are translated.

Please review it and let me know of any pointers

**Comment by mauriciogracia** [comment]
@sdottaka There are a few texts that require translation still, but I have reached 95%

feel free to merge this and thanks

**Comment by sdottaka** [comment]
Merged.
Thank you!

**Comment by mauriciogracia** [comment]
Thanks for all your help

**Pull request merged**
