### PR TITLE
Feature Request: Move To Next File option while comparing files #475 …

### PR DESCRIPTION
**Pull request by ranjwarrior**
…- Navigating between files in file comparison mode. Will attempt to move to first/next/prev/last files only, ignoring/skipping directories.
(Note: Keyboard navigation, or any other missing options can be added if required)

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you!

**Comment by ranjwarrior** [comment]
Thanks for merging. Happy to contribute.

**Comment by jschof** [comment]
Thanks @ranjwarrior it's appreciated!

**Comment by mrnams** [comment]
How to disable it? I want to disable auto move to next file

**Comment by sdottaka** [comment]
By default, it does not move to the next file automatically and displays a message box asking "Do you want to move to the next file?".
You probably checked the "Don't ask this question again" checkbox in the message box to prevent it from appearing.
If you want this message box to appear again, uncheck the checkbox in the [Message Boxes] category in the Options window.
Or, I think the Answer column in this [Message Boxes] category is set to "Yes", so if you set it to "No" and leave the checkbox checked, it will not move to the next file.

image

**Pull request merged**
