### PR TITLE
Update of Lithuanian translation

### PR DESCRIPTION
**Pull request by Tichij**

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Update of Slovenian translation 
per date 25.12.2020.

**Comment by JadranR** [comment]
Update of Slovenian translation WinMerge
per date 25.12.2020.
Best Regards,
Jadran
[Translations.zip](https://github.com/WinMerge/winmerge/files/5749905/Translations.zip)

**Comment by JadranR** [comment]
Update of Slovenian translation winMerge
per date 25.12.2020.

Best Regards,
Jadran
[Translations.zip](https://github.com/WinMerge/winmerge/files/5749909/Translations.zip)

**Comment by sdottaka** [comment]
@JadranR Thank you for the translation. Your translation has been merged. However, this is the Lithuanian translation Pull Request page, so the next time you update your translation, please create a new issue or Pull Request.

**Comment by JadranR** [comment]
Hi,

Please if you can send me the latest version of the language file, which I can update for Slovenian. Currently, there are quite a few English strings in the latest version of the app.

With respect,
Jadran Rudec

**Pull request merged**
