### PR TITLE
Add PreviewPlantUML plugin

### PR DESCRIPTION
**Pull request by sdottaka**
This PR adds a plugin that converts PlantUML files to png files using the plantuml.jar command and displays the converted png files in the Image Compare window.

This plugin requires Java and Graphviz to be installed.
The plantuml-*.jar files are not shipped with WinMerge and will be downloaded when the plugin is run.

image

### CODE REVIEW

**Comment by JadranR** [comment]
How I can here translate Slovenian language file for this plugin  or download it on My PC ?
Best Regards,
Jadran

**Comment by JadranR** [comment]
Can you turn on the option to directly editing the plugin language file here

Best Regards,
Jadran

**Comment by JadranR** [comment]
Slovenian updated translation WinMerge 2.16.25-93865baad, per Today.
Best regards,
Jadran
[Slovenian_WinMerge 2.16.25-93865baad.zip](https://github.com/WinMerge/winmerge/files/10417024/Slovenian_WinMerge.2.16.25-93865baad.zip)

**Comment by sdottaka** [comment]
Thank you for the translation.

Perhaps after editing with the edit button, you can create a PullRequest. If it doesn't work, deleting https://github.com/JadranR/winmerge/ may work.

**Pull request merged**
