### PR TITLE
Add One-Hand mice wheel scroll diff and merge

### PR DESCRIPTION
**Pull request by lededev**
The current version of WinMerge primarily supports two-handed operation. While toolbar buttons can be used with one hand, constantly shifting your gaze between the main text and the toolbar is inefficient. Some users, such as those with disabilities or those who have one hand occupied (e.g., during a phone call or while drinking), need to operate common functions efficiently with one hand.

This code introduces the following one-handed operations:

Hold the right mouse button and roll the mouse wheel up: equivalent to Alt+Up
Hold the right mouse button and roll the mouse wheel down: equivalent to Alt+Down
Hold the right mouse button and roll the mouse wheel left: equivalent to Alt+Left
Hold the right mouse button and roll the mouse wheel right: equivalent to Alt+Right

Note: If you have any global mouse stroke/gesture app running, add WinMergeU.exe to its ignore list for these shortcuts to take effect. Alternatively, you can use your global mouse gesture program to customize more functions and ignore this built-in feature.

For users who prefer using the left hand for the keyboard and the right hand for the mouse, the following shortcuts are added:

Alt + roll the mouse wheel up: equivalent to Alt+Up
Alt + roll the mouse wheel down: equivalent to Alt+Down
Alt + roll the mouse wheel left: equivalent to Alt+Left
Alt + roll the mouse wheel right: equivalent to Alt+Right
Ctrl + Alt + roll the mouse wheel left: equivalent to Ctrl+Alt+Left
Ctrl + Alt + roll the mouse wheel right: equivalent to Ctrl+Alt+Right

Additionally, for users whose mice lack horizontal scroll wheels, an alternative mode is provided:

Alt + Shift + scroll the mouse wheel up: equivalent to Alt+Left
Alt + Shift + scroll the mouse wheel down: equivalent to Alt+Right
Ctrl + Alt + Shift + scroll the mouse wheel up: equivalent to Ctrl+Alt+Left
Ctrl + Alt + Shift + scroll the mouse wheel down: equivalent to Ctrl+Alt+Right

User Tips: To keep the user interface and menus simple, these shortcuts are not added to the menu items. Only the floating tooltip text of the toolbar button shows these new shortcuts in multiple lines.

f20240917T174813

Language Translation Restrictions: The floating prompt text of the MFC CToolBar is limited to 256 UNICODE characters. Therefore, the translation context for these shortcut keys must be limited to this number of characters, as extra characters will be truncated and cannot be displayed. To reduce the number of words, you can use UNICODE characters such as emojis and direction symbols (⏬⏫🔼🔽▶️◀️) to replace text descriptions, as these symbols only take up one UNICODE character.

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you for the PR.

I feel that the tooltip display is a little difficult to understand and has lost consistency with other displays. Would it be okay to delete some parts as shown below and modify it to include them in the manual instead?

Next Difference |Alt+Down\nRightButton+ScrollDown\nAlt+ScrollDown
↓
Next Difference (Alt+Down / Right Button+Wheel Down)

**Comment by lededev** [comment]
If there is someone can rewrite the MFC/ATL CommCtrl.h `szText` 40 UNICODE characters limit, or a reimpliment tooltips class, without 40 UNICODE characters limit, it will be easy to show full usage information in all Languages.
```
typedef struct tagNMTTDISPINFOW {
    NMHDR hdr;
    LPWSTR lpszText;
    WCHAR szText[80];
    HINSTANCE hinst;
    UINT uFlags;
    LPARAM lParam;
} NMTTDISPINFOW, *LPNMTTDISPINFOW;

```

**Comment by lededev** [comment]
English 78 chars, with only `\n` 1 char as separator. If use ` / ` 3 chars as separator, you need shorten text.
image

**Comment by lededev** [comment]
I am not English user, it is OK to me reduce tooltip information, for a better display layout, anyway, in Chinese it can fully presented.
You may change them to any form you like.

**Comment by lededev** [comment]
I use smart pointer extend tooltip text lenght from 80 to 256 characters. Now all Languages have enough lenght.
image

**Comment by sdottaka** [comment]
For simplicity's sake, I wanted to have just two displays, one for keyboard operations and one for mouse operations, but I merged them for now.

This added operation doesn't work in the folder comparison window, image comparison window, etc., so later I may change the tooltip display depending on the active window.

**Comment by lededev** [comment]
OK, I suggest providing complete usage information in at least one place on the software, because I've noticed that very few Windows users read the manual.

**Pull request merged**
