### PR TITLE
Italian language update

### PR DESCRIPTION
**Pull request by bovirus**
@sdottaka 

**- Shell translation (100% translated)**
Complete Italian tranbslation for shell extension

**- GUI translation (100% translated)**
Complete Italian translation for GUI

**- Inno Setup Installer scripts**
Add Italian custom strings

Please merge. Thanks.

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you!

**Comment by bovirus** [comment]
@sdottaka 

In this web page https://winmerge.org/translations/

could you plrase add my nick (bovirus) at Italian translator?
could update thr translation statistics about languages (latest update was 27.01.2024).

Thanks.

**Comment by sdottaka** [comment]
The information in the above URL is created from the header section of the Italian.po file.
I added your name in commit [72196dc](https://github.com/WinMerge/winmerge/commit/72196dc238b27e875d940a67ab76232d114f9f02).
It will probably be reflected in the next stable release (2024-4-27),
You can also check the URL below.
https://github.com/WinMerge/winmerge/blob/master/Translations/TranslationsStatus.md

**Comment by bovirus** [comment]
@sdottaka 

Please modify python 

https://github.com/bovirus/winmerge/blob/master/Translations/GetTranslationsStatus.py

to get date for Shell Extension italian language
to get info from Inno Setup Custom Message file (and add Italian translation line for custo messages translated at 100%)

I propose to change the header of tramslation status

## WinMerge -> ## GUI
## Inno Setup -> ## Inno Setup Custom Messages

Thanks.

**Comment by sdottaka** [comment]
I'm not familiar with Python so any PR would be appreciated.

**Pull request merged**
