### PR TITLE
Add One-Hand mice wheel scroll diff and merge

### PR DESCRIPTION
**Pull request by lededev**
There is a stable version for both DirView and MergeEditView, without Hooks.

### CODE REVIEW

**Comment by sdottaka** [comment]
Thank you for the PR!
The reason I insisted on the hook is because I wanted this function to be applied to the Image compare window, Binary compare window, and Webpage compare window.
I'll give up for now.
There is a conflict. Can you resolve it?

**Comment by lededev** [comment]
Any view want this feature, need only add 4 lines:
```
BOOL SomeView::PreTranslateMessage(MSG* pMsg)
{
+	if (CMouseHook::PreTranslateMessage(pMsg))
+		return TRUE;

LRESULT SomeView::WindowProc(UINT message, WPARAM wParam, LPARAM lParam)
{
+	if (CMouseHook::CallWindowProc(message, wParam, lParam))
+		return 0;

```

**Comment by sdottaka** [comment]
> Any view want this feature, need only add 4 lines:
> 
> ```
> BOOL SomeView::PreTranslateMessage(MSG* pMsg)
> {
> +	if (CMouseHook::PreTranslateMessage(pMsg))
> +		return TRUE;
> 
> LRESULT SomeView::WindowProc(UINT message, WPARAM wParam, LPARAM lParam)
> {
> +	if (CMouseHook::CallWindowProc(message, wParam, lParam))
> +		return 0;
> ```

Some parts such as Image compare window are implemented in external DLL. Will it still work?

**Comment by lededev** [comment]
> Some parts such as Image compare window are implemented in external DLL. Will it still work?

If those DLL compile with MouseHook.cpp and MouseHook.h, it should work, all function using PostMessage.

**Comment by sdottaka** [comment]
Ok... I wanted to avoid implementing it separately in a DLL...

**Comment by lededev** [comment]
I think you can delete MouseHook.cpp and make MouseHook.h as a header only lib.

**Comment by sdottaka** [comment]
Just to be sure, did the commit below not solve your problem or do you feel the hook is inappropriate?

https://github.com/WinMerge/winmerge/commit/4fb7ddec58dc4155dfadde81943ae97f3a37cbaf

**Comment by lededev** [comment]
> Just to be sure, did the commit below not solve your problem or do you feel the hook is inappropriate?
> 
> [4fb7dde](https://github.com/WinMerge/winmerge/commit/4fb7ddec58dc4155dfadde81943ae97f3a37cbaf)

This commit works fine in DirView and MergeEditView after launching multiple instances. I think Hooks in a single process are also OK as long as they work properly. I will close this PR and continue testing the beta version.

**Comment by sdottaka** [comment]
Anyway, thanks for your confirmation and PR.

**Pull request closed without merging**
